// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaDktbA7qgpnZy1gZBde4vv9i8GSYuQuQ',
    appId: '1:794800322831:web:4406cbedd8d10147dae67a',
    messagingSenderId: '794800322831',
    projectId: 'emergency-accident-alert',
    authDomain: 'emergency-accident-alert.firebaseapp.com',
    databaseURL: 'https://emergency-accident-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emergency-accident-alert.appspot.com',
    measurementId: 'G-XLBEWRE231',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdJbIsoJ79PuAm0vj4TEZ7gbkWxQY1jA',
    appId: '1:794800322831:android:d6a748478b5230c6dae67a',
    messagingSenderId: '794800322831',
    projectId: 'emergency-accident-alert',
    databaseURL: 'https://emergency-accident-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emergency-accident-alert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDWDPFiQM-9o6yToPd-yFUxDFBROghmw',
    appId: '1:794800322831:ios:aa6c38c2585cf53edae67a',
    messagingSenderId: '794800322831',
    projectId: 'emergency-accident-alert',
    databaseURL: 'https://emergency-accident-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emergency-accident-alert.appspot.com',
    iosClientId: '794800322831-ltv0tginc5vimlbcnfq39kblg43nqh0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDWDPFiQM-9o6yToPd-yFUxDFBROghmw',
    appId: '1:794800322831:ios:aa6c38c2585cf53edae67a',
    messagingSenderId: '794800322831',
    projectId: 'emergency-accident-alert',
    databaseURL: 'https://emergency-accident-alert-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emergency-accident-alert.appspot.com',
    iosClientId: '794800322831-ltv0tginc5vimlbcnfq39kblg43nqh0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertWeb',
  );
}
